name: tests unitaires
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.8","3.10"]
    runs-on: ubuntu-latest
    steps:
      - run : echo "Branch:${{github.ref}}"
      - run : echo "OS:${{runner.os}}"
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - run: echo "python --version"
      - name: Set up Pytest
        run: python -m pip install pytest
      - name: Run tests
        run: python3 -m pytest TP1/test.py
